#!/usr/bin/env bash
mk() {
     gcc $* -fobjc-arc -Wall -Wno-deprecated-declarations -I src src/cocoaarc.m -framework OpenGL -framework AppKit
}
install -d b
mk test/simple.c -o b/simple
mk test/test.c -o b/test
mk test/glestest.c -o b/glestest
