#+TITLE:     GLGS
#+AUTHOR:    Jorge Acereda
#+EMAIL:     jacereda@gmail.com
#+DATE:      2011-10-02 Sun
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:1 num:t toc:t \n:nil @:t ::t |:t ^:{} -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT: 

* Export 							   :noexport:
#+begin_src emacs-lisp :results silent
(save-excursion 
  (org-export-as-utf8 1)
  (rename-file "README.txt" "README" t))
(save-excursion 
  (org-export-as-html 1))
#+end_src
file:README
file:README.html

* Purpose
GLGS is a small screen/event handling library that provides a thin
layer abstracting the details of configuring the screen and handling
input. Sort of a simple GLUT/SDL.
* Building
As of now, the build scripts only work on Mac OS X.
** Targets
*** IOS
The following command should build the library and the examples and
install them in the IOS simulator directory.
#+begin_src sh
./mk-ios
#+end_src
*** Android
The following command should build the library and the examples and
install them in the Android emulator. The emulator must be running.
#+begin_src sh
./mk-android
#+end_src
*** NPAPI
The following command should build the library and the examples and
install them in the user's plugins directory.
#+begin_src sh
./mk-npapi
#+end_src
After building, try opening file:testplugin.html
* API
** Functions
*** Application hook
**** intptr_t event(const ev * e);
This is the event handling routine implemented by your application.
*** Screen properties
**** unsigned gsWidth();
Current screen width
**** unsigned gsHeight();
Current screen height
*** Mouse location
**** int gsMouseX();
Current X mouse position
**** int gsMouseY();
Current Y mouse position
*** Keyboard
**** int gsPressed(gskey key);
True if key is currently pressed
**** int gsReleased(gskey key);
True if key has just been released
**** int gsShowKeyboard();
On platforms that support it, show the on-screen keyboard
**** int gsHideKeyboard();
On platforms that support it, hide the on-screen keyboard
*** Resources
**** const char * gsResPath();
Resources path
*** Logging
**** void gsReportV(const char * fmt, va_list ap);
Report a message (depending on the platform, it might go to a file)
**** void gsReport(const char * fmt, ...);
Report a message (depending on the platform, it might go to a file)
*** Events
**** int evType(const ev *);
Event type.
**** const char * evName(const ev *);
Event name.
**** int evWidth(const ev *);
Width for GSE_RESIZE events.
**** int evHeight(const ev *);
Width for GSE_RESIZE events.
**** gskey evWhich(const ev *);
Keycode associated to GSE_DOWN/GSE_UP events.
**** const char * evKeyName(const ev *);
Key name for GSE_DOWN/GSE_UP events.
**** int evX(const ev *);
Mouse X position for GSE_DOWN/GSE_UP events.
**** int evY(const ev *);
Mouse Y position for GSE_DOWN/GSE_UP events.
**** int evArgC(const ev *);
Argument count for GSE_INIT events.
**** char ** evArgV(const ev *);
Argument array for GSE_INIT events.
**** intptr_t evArg0(const ev *);
First event argument, mostly internal.
**** intptr_t evArg1(const ev *);

Second event argument, mostly internal.
**** intptr_t gsInject(gseventtype, intptr_t, intptr_t);
Inject an event, mostly internal.

** Events
*** GSE_NONE
Null event, must be ignored.
*** GSE_INIT
Called upon initialization, no GL operations should be performed at this stage.
*** GSE_TERM
Called befor terminating the application.
*** GSE_GLINIT
The OpenGL context has been established. Might be called several times.
*** GL_EVENT_GLTERM
The OpenGL context is going to be destroyed. Might be called several times.
*** GSE_UPDATE
This is your update routine, should be called at ~60Hz.
*** GSE_RESIZE
Called when the screen is resized. Might be called several times.
*** GSE_DOWN
A key/button has been pressed.
*** GSE_UP
A key/button has been released.
*** GSE_UNICODE
Called when the user enters text.
*** GSE_MOTION
The mouse moved.
*** GSE_CLOSE
The application is about to close.
*** GSE_INVOKE
Invoke method. The argument is available as evMethod().

* License
  Copyright (c) 2011, Jorge Acereda Maciá
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:
        
  1. Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
        
  2. Redistributions in binary form must reproduce the above copyright
     notice, this list of conditions and the following disclaimer in
     the documentation and/or other materials provided with the
     distribution.

  3. Neither the name of the author nor the names of its contributors
     may be used to endorse or promote products derived from this
     software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT
  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
